set(_CATKIN_CURRENT_PACKAGE "sensor_publishing")
set(sensor_publishing_VERSION "0.0.0")
set(sensor_publishing_MAINTAINER "lukuky64 <lukuky64@todo.todo>")
set(sensor_publishing_PACKAGE_FORMAT "2")
set(sensor_publishing_BUILD_DEPENDS "roscpp" "sensor_msgs")
set(sensor_publishing_BUILD_EXPORT_DEPENDS "roscpp" "sensor_msgs")
set(sensor_publishing_BUILDTOOL_DEPENDS "catkin")
set(sensor_publishing_BUILDTOOL_EXPORT_DEPENDS )
set(sensor_publishing_EXEC_DEPENDS "roscpp" "sensor_msgs")
set(sensor_publishing_RUN_DEPENDS "roscpp" "sensor_msgs")
set(sensor_publishing_TEST_DEPENDS )
set(sensor_publishing_DOC_DEPENDS )
set(sensor_publishing_URL_WEBSITE "")
set(sensor_publishing_URL_BUGTRACKER "")
set(sensor_publishing_URL_REPOSITORY "")
set(sensor_publishing_DEPRECATED "")